name = "na-hitokoto-content" # 您可以自定义 Worker 的名称
main = "src/index.js"
compatibility_date = "2024-04-05"

routes = [
    { pattern = "content.hitokoto.natsuki.cloud", custom_domain = true }
]

# 绑定 KV 命名空间
# 您需要在 Cloudflare Dashboard 中创建一个 KV 命名空间
# 然后将它的 ID 粘贴到下面
# wrangler kv:namespace create TEXT_CACHE
[[kv_namespaces]]
binding = "TEXT_CACHE"
id = "da58941aa79b41c890f4d2f155dc658a" # <--- 请替换成您的 KV Namespace ID

# 定义构建规则，以确保 .txt 文件能被正确加载
[[rules]]
type = "Text"
globs = ["**/*.txt"]


# 添加 Cron 触发器
# "0 * * * *" 表示在每小时的第 0 分钟执行
[triggers]
crons = ["0 * * * *"]

# 变量和密钥声明
# 生产环境中的值应在 Cloudflare Dashboard 中设置
# 这种方式使得配置更加清晰，并且便于本地开发（配合 .dev.vars 文件）
[vars]
GEMINI_API_KEY = "" # 占位符，请在 Dashboard 中设置生产环境的值
UPDATE_TOKEN = ""   # 占位符，请在 Dashboard 中设置生产环境的值

#enable log
[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
